# Generated by Django 4.1 on 2022-08-05 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0003_pontoturistco_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistco',
            name='enderecos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco'),
            preserve_default=False,
        ),
    ]
